### ISSUE TITLE
اختيار اسم ونوع المشروع

### ISSUE THREAD

**Issue by Amin0x** [amin-omer/OpenDev#1]
نرجو المشاركة في اختيار المشروع بعرض اقتراح 
 لمشروع App للاندرويد والتصويت علي المشاريع المقترحة

**Comment by Amin0x** [comment]
مرحب بكل القادمين

اول لدينا حاجتين لازم نعملها 

- الاولي هي تقديم اقتراحات لافكار لمشاريع أندرويد لتنفيذها
 واختيار فكرة مشروع واحدة بالتوافق مع بعضنا اليعض
- اختيار اسم للمشروع

**Comment by pysuhaib** [comment]
السلام عليكم 
بقترح انو في البدايه نشتغل مشروع 
بسيط بغطي الاساسيات وبعداك نتوسع

**Comment by Amin0x** [comment]
> السلام عليكم
> بقترح انو في البدايه نشتغل مشروع
> بسيط بغطي الاساسيات وبعداك نتوسع

تمام 
بس ادينا اقتراح لتطبيق

**Comment by sarah-salaheldeen** [comment]
السلام عليكم 
ممكن نبدأ بchat app مثلا 
لأنه بيغطي تقريبا كل الأساسيات
أو تطبيق متجر الكتروني
وبقترح كمان نعمل قروب في slack مثلا أو اي برنامج مشابه
بس عشان التواصل بكون أسهل

**Comment by Amin0x** [comment]
> السلام عليكم
> ممكن نبدأ بchat app مثلا
> لأنه بيغطي تقريبا كل الأساسيات
> أو تطبيق متجر الكتروني
> وبقترح كمان نعمل قروب في slack مثلا أو اي برنامج مشابه
> بس عشان التواصل بكون أسهل

 فكرة ممتازة انا برضو اقترحي متجر
الإلكتروني 

اما بالنسبة للقروب فعندنا واحد معمول في قوقل قروب 
علي الرابط 
https://groups.google.com/forum/?nomobile=true#!forum/aminproject

**Comment by Moezzain** [comment]
السلام عليكم
برضو من ال basic apps
تطبيق ال toDo list 
لو دايرين حاجة بسيطة شديد.
تتحفظ في DB 
و تظهر في UI.
لكن متجر برضو قدام

**Comment by Moezzain** [comment]
> 
> 
> > السلام عليكم
> > ممكن نبدأ بchat app مثلا
> > لأنه بيغطي تقريبا كل الأساسيات
> > أو تطبيق متجر الكتروني
> > وبقترح كمان نعمل قروب في slack مثلا أو اي برنامج مشابه
> > بس عشان التواصل بكون أسهل
> 
> فكرة ممتازة انا برضو اقترحي متجر
> الإلكتروني
> 
> اما بالنسبة للقروب فعندنا واحد معمول في قوقل قروب
> علي الرابط
> https://groups.google.com/forum/?nomobile=true#!forum/aminproject

ما خشة معاي

**Comment by amin-omer** [comment]
> > > السلام عليكم
> > > ممكن نبدأ بchat app مثلا
> > > لأنه بيغطي تقريبا كل الأساسيات
> > > أو تطبيق متجر الكتروني
> > > وبقترح كمان نعمل قروب في slack مثلا أو اي برنامج مشابه
> > > بس عشان التواصل بكون أسهل
> > 
> > 
> > فكرة ممتازة انا برضو اقترحي متجر
> > الإلكتروني
> > اما بالنسبة للقروب فعندنا واحد معمول في قوقل قروب
> > علي الرابط
> > https://groups.google.com/forum/?nomobile=true#!forum/aminproject
> 
> ما خشة معاي

https://groups.google.com/d/forum/aminproject

**Comment by Moezzain** [comment]
> 
> 
> > > > السلام عليكم
> > > > ممكن نبدأ بchat app مثلا
> > > > لأنه بيغطي تقريبا كل الأساسيات
> > > > أو تطبيق متجر الكتروني
> > > > وبقترح كمان نعمل قروب في slack مثلا أو اي برنامج مشابه
> > > > بس عشان التواصل بكون أسهل
> > > 
> > > 
> > > فكرة ممتازة انا برضو اقترحي متجر
> > > الإلكتروني
> > > اما بالنسبة للقروب فعندنا واحد معمول في قوقل قروب
> > > علي الرابط
> > > https://groups.google.com/forum/?nomobile=true#!forum/aminproject
> > 
> > 
> > ما خشة معاي
> 
> https://groups.google.com/d/forum/aminproject

غير مسموح لك بالوصول إلى هذا المحتوى. (#418)

**Comment by amin-omer** [comment]
> > > > > السلام عليكم
> > > > > ممكن نبدأ بchat app مثلا
> > > > > لأنه بيغطي تقريبا كل الأساسيات
> > > > > أو تطبيق متجر الكتروني
> > > > > وبقترح كمان نعمل قروب في slack مثلا أو اي برنامج مشابه
> > > > > بس عشان التواصل بكون أسهل
> > > > 
> > > > 
> > > > فكرة ممتازة انا برضو اقترحي متجر
> > > > الإلكتروني
> > > > اما بالنسبة للقروب فعندنا واحد معمول في قوقل قروب
> > > > علي الرابط
> > > > https://groups.google.com/forum/?nomobile=true#!forum/aminproject
> > > 
> > > 
> > > ما خشة معاي
> > 
> > 
> > https://groups.google.com/d/forum/aminproject
> 
> غير مسموح لك بالوصول إلى هذا المحتوى. (#418)

لازم تسجل دخول لقوقل

**Comment by Moezzain** [comment]
> 
> 
> > > > > > السلام عليكم
> > > > > > ممكن نبدأ بchat app مثلا
> > > > > > لأنه بيغطي تقريبا كل الأساسيات
> > > > > > أو تطبيق متجر الكتروني
> > > > > > وبقترح كمان نعمل قروب في slack مثلا أو اي برنامج مشابه
> > > > > > بس عشان التواصل بكون أسهل
> > > > > 
> > > > > 
> > > > > فكرة ممتازة انا برضو اقترحي متجر
> > > > > الإلكتروني
> > > > > اما بالنسبة للقروب فعندنا واحد معمول في قوقل قروب
> > > > > علي الرابط
> > > > > https://groups.google.com/forum/?nomobile=true#!forum/aminproject
> > > > 
> > > > 
> > > > ما خشة معاي
> > > 
> > > 
> > > https://groups.google.com/d/forum/aminproject
> > 
> > 
> > غير مسموح لك بالوصول إلى هذا المحتوى. (#418)
> 
> لازم تسجل دخول لقوقل

Already signed in.

**Comment by amin-omer** [comment]
> > > > > > > السلام عليكم
> > > > > > > ممكن نبدأ بchat app مثلا
> > > > > > > لأنه بيغطي تقريبا كل الأساسيات
> > > > > > > أو تطبيق متجر الكتروني
> > > > > > > وبقترح كمان نعمل قروب في slack مثلا أو اي برنامج مشابه
> > > > > > > بس عشان التواصل بكون أسهل
> > > > > > 
> > > > > > 
> > > > > > فكرة ممتازة انا برضو اقترحي متجر
> > > > > > الإلكتروني
> > > > > > اما بالنسبة للقروب فعندنا واحد معمول في قوقل قروب
> > > > > > علي الرابط
> > > > > > https://groups.google.com/forum/?nomobile=true#!forum/aminproject
> > > > > 
> > > > > 
> > > > > ما خشة معاي
> > > > 
> > > > 
> > > > https://groups.google.com/d/forum/aminproject
> > > 
> > > 
> > > غير مسموح لك بالوصول إلى هذا المحتوى. (#418)
> > 
> > 
> > لازم تسجل دخول لقوقل
> 
> Already signed in.

صلحت المشكلة حاول تاني

**Comment by Moezzain** [comment]
> 
> 
> > > > > > السلام عليكم
> > > > > > ممكن نبدأ بchat app مثلا
> > > > > > لأنه بيغطي تقريبا كل الأساسيات
> > > > > > أو تطبيق متجر الكتروني
> > > > > > وبقترح كمان نعمل قروب في slack مثلا أو اي برنامج مشابه
> > > > > > بس عشان التواصل بكون أسهل
> > > > > 
> > > > > 
> > > > > فكرة ممتازة انا برضو اقترحي متجر
> > > > > الإلكتروني
> > > > > اما بالنسبة للقروب فعندنا واحد معمول في قوقل قروب
> > > > > علي الرابط
> > > > > https://groups.google.com/forum/?nomobile=true#!forum/aminproject
> > > > 
> > > > 
> > > > ما خشة معاي
> > > 
> > > 
> > > https://groups.google.com/d/forum/aminproject
> > 
> > 
> > غير مسموح لك بالوصول إلى هذا المحتوى. (#418)
> 
> لازم تسجل دخول لقوقل

go to your  group setting  https://groups.google.com/forum/#!groupsettings/YourGroups Name 
 
then    Manage Group > Information > Directory - "Group directory" - the setting to be set to "Anyone on the web" or else users who aren't members won't be able to discover the group at all as result of recent changes.
كدي جرب أعمل كدة لي اعدادات القروب

**Comment by Moezzain** [comment]
> 
> 
> > > > > > > > السلام عليكم
> > > > > > > > ممكن نبدأ بchat app مثلا
> > > > > > > > لأنه بيغطي تقريبا كل الأساسيات
> > > > > > > > أو تطبيق متجر الكتروني
> > > > > > > > وبقترح كمان نعمل قروب في slack مثلا أو اي برنامج مشابه
> > > > > > > > بس عشان التواصل بكون أسهل
> > > > > > > 
> > > > > > > 
> > > > > > > فكرة ممتازة انا برضو اقترحي متجر
> > > > > > > الإلكتروني
> > > > > > > اما بالنسبة للقروب فعندنا واحد معمول في قوقل قروب
> > > > > > > علي الرابط
> > > > > > > https://groups.google.com/forum/?nomobile=true#!forum/aminproject
> > > > > > 
> > > > > > 
> > > > > > ما خشة معاي
> > > > > 
> > > > > 
> > > > > https://groups.google.com/d/forum/aminproject
> > > > 
> > > > 
> > > > غير مسموح لك بالوصول إلى هذا المحتوى. (#418)
> > > 
> > > 
> > > لازم تسجل دخول لقوقل
> > 
> > 
> > Already signed in.
> 
> صلحت المشكلة حاول تاني


Project Forum
You must be a member of this group to view and participate in it.

Apply for membership or contact the owner and the manager.
Report this group.

أعمل لي Add

**Comment by amin-omer** [comment]
> > > > > > > السلام عليكم
> > > > > > > ممكن نبدأ بchat app مثلا
> > > > > > > لأنه بيغطي تقريبا كل الأساسيات
> > > > > > > أو تطبيق متجر الكتروني
> > > > > > > وبقترح كمان نعمل قروب في slack مثلا أو اي برنامج مشابه
> > > > > > > بس عشان التواصل بكون أسهل
> > > > > > 
> > > > > > 
> > > > > > فكرة ممتازة انا برضو اقترحي متجر
> > > > > > الإلكتروني
> > > > > > اما بالنسبة للقروب فعندنا واحد معمول في قوقل قروب
> > > > > > علي الرابط
> > > > > > https://groups.google.com/forum/?nomobile=true#!forum/aminproject
> > > > > 
> > > > > 
> > > > > ما خشة معاي
> > > > 
> > > > 
> > > > https://groups.google.com/d/forum/aminproject
> > > 
> > > 
> > > غير مسموح لك بالوصول إلى هذا المحتوى. (#418)
> > 
> > 
> > لازم تسجل دخول لقوقل
> 
> go to your group setting https://groups.google.com/forum/#!groupsettings/YourGroups Name
> 
> then Manage Group > Information > Directory - "Group directory" - the setting to be set to "Anyone on the web" or else users who aren't members won't be able to discover the group at all as result of recent changes.
> كدي جرب أعمل كدة لي اعدادات القروب

ايوة صحيح

**Comment by amin-omer** [comment]
> > > > > > > > > السلام عليكم
> > > > > > > > > ممكن نبدأ بchat app مثلا
> > > > > > > > > لأنه بيغطي تقريبا كل الأساسيات
> > > > > > > > > أو تطبيق متجر الكتروني
> > > > > > > > > وبقترح كمان نعمل قروب في slack مثلا أو اي برنامج مشابه
> > > > > > > > > بس عشان التواصل بكون أسهل
> > > > > > > > 
> > > > > > > > 
> > > > > > > > فكرة ممتازة انا برضو اقترحي متجر
> > > > > > > > الإلكتروني
> > > > > > > > اما بالنسبة للقروب فعندنا واحد معمول في قوقل قروب
> > > > > > > > علي الرابط
> > > > > > > > https://groups.google.com/forum/?nomobile=true#!forum/aminproject
> > > > > > > 
> > > > > > > 
> > > > > > > ما خشة معاي
> > > > > > 
> > > > > > 
> > > > > > https://groups.google.com/d/forum/aminproject
> > > > > 
> > > > > 
> > > > > غير مسموح لك بالوصول إلى هذا المحتوى. (#418)
> > > > 
> > > > 
> > > > لازم تسجل دخول لقوقل
> > > 
> > > 
> > > Already signed in.
> > 
> > 
> > صلحت المشكلة حاول تاني
> 
> Project Forum
> You must be a member of this group to view and participate in it.
> 
> Apply for membership or contact the owner and the manager.
> Report this group.
> 
> أعمل لي Add

اديني الايميل 
أو انت اعمل 
Request

**Comment by amin-omer** [comment]
> > > > > > > > > > السلام عليكم
> > > > > > > > > > ممكن نبدأ بchat app مثلا
> > > > > > > > > > لأنه بيغطي تقريبا كل الأساسيات
> > > > > > > > > > أو تطبيق متجر الكتروني
> > > > > > > > > > وبقترح كمان نعمل قروب في slack مثلا أو اي برنامج مشابه
> > > > > > > > > > بس عشان التواصل بكون أسهل
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > فكرة ممتازة انا برضو اقترحي متجر
> > > > > > > > > الإلكتروني
> > > > > > > > > اما بالنسبة للقروب فعندنا واحد معمول في قوقل قروب
> > > > > > > > > علي الرابط
> > > > > > > > > https://groups.google.com/forum/?nomobile=true#!forum/aminproject
> > > > > > > > 
> > > > > > > > 
> > > > > > > > ما خشة معاي
> > > > > > > 
> > > > > > > 
> > > > > > > https://groups.google.com/d/forum/aminproject
> > > > > > 
> > > > > > 
> > > > > > غير مسموح لك بالوصول إلى هذا المحتوى. (#418)
> > > > > 
> > > > > 
> > > > > لازم تسجل دخول لقوقل
> > > > 
> > > > 
> > > > Already signed in.
> > > 
> > > 
> > > صلحت المشكلة حاول تاني
> > 
> > 
> > Project Forum
> > You must be a member of this group to view and participate in it.
> > Apply for membership or contact the owner and the manager.
> > Report this group.
> > أعمل لي Add
> 
> اديني الايميل
> أو انت اعمل
> Request

اضفتك

**Comment by Moezzain** [comment]
> 
> 
> > > > > > > > > > السلام عليكم
> > > > > > > > > > ممكن نبدأ بchat app مثلا
> > > > > > > > > > لأنه بيغطي تقريبا كل الأساسيات
> > > > > > > > > > أو تطبيق متجر الكتروني
> > > > > > > > > > وبقترح كمان نعمل قروب في slack مثلا أو اي برنامج مشابه
> > > > > > > > > > بس عشان التواصل بكون أسهل
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > فكرة ممتازة انا برضو اقترحي متجر
> > > > > > > > > الإلكتروني
> > > > > > > > > اما بالنسبة للقروب فعندنا واحد معمول في قوقل قروب
> > > > > > > > > علي الرابط
> > > > > > > > > https://groups.google.com/forum/?nomobile=true#!forum/aminproject
> > > > > > > > 
> > > > > > > > 
> > > > > > > > ما خشة معاي
> > > > > > > 
> > > > > > > 
> > > > > > > https://groups.google.com/d/forum/aminproject
> > > > > > 
> > > > > > 
> > > > > > غير مسموح لك بالوصول إلى هذا المحتوى. (#418)
> > > > > 
> > > > > 
> > > > > لازم تسجل دخول لقوقل
> > > > 
> > > > 
> > > > Already signed in.
> > > 
> > > 
> > > صلحت المشكلة حاول تاني
> > 
> > 
> > Project Forum
> > You must be a member of this group to view and participate in it.
> > Apply for membership or contact the owner and the manager.
> > Report this group.
> > أعمل لي Add
> 
> اديني الايميل
> أو انت اعمل
> Request

Your membership is pending

Your membership to this group is pending approval.

moezzain94@gmail.com

**Comment by amin-omer** [comment]
> 
> Your membership is pending
> 
> Your membership to this group is pending approval.
> 
> [moezzain94@gmail.com](mailto:moezzain94@gmail.com)

**Comment by Amin0x** [comment]
يعني خلاص كدا الناس اتفقت علي برنامج متجر الإلكتروني ولا ننتظر ونشوف لو في اقتراحات
تانية 

ارجو التعقيب

**Comment by Moezzain** [comment]
> 
> 
> يعني خلاص كدا الناس اتفقت علي برنامج متجر الإلكتروني ولا ننتظر ونشوف لو في اقتراحات
> تانية
> 
> ارجو التعقيب

أنا ما عندي مشكلة

**Comment by Amin0x** [comment]
> > يعني خلاص كدا الناس اتفقت علي برنامج متجر الإلكتروني ولا ننتظر ونشوف لو في اقتراحات
> > تانية
> > ارجو التعقيب
> 
> أنا ما عندي مشكلة

خلاص تمام 
حاقفل الايشو دي ونفتح اشو تانية 
نحدد بيها الخطوط العامة للتطبيق 
ومتطلبات النظام 
وح ارفع ملفات المشروع
